apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-new
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: nginx-ingress-controller
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.3.12
    helm:
      values: |
        image:
          tag: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

